# Generated by Django 4.1 on 2023-05-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_deck_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='num_cards',
            field=models.JSONField(default=[0, 0, 0, 0, 0, 0, 0]),
        ),
    ]
